services:
  app:
    build: .
    container_name: adonis
    env_file:
        .env
    ports:
      - "3333:3333"
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
